#!/bin/sh
# /etc/init.d/network: start/stop the network interface
# chkconfig: 2345 04 96
set -a

PATH=/sbin:/bin:/usr/bin:/usr/sbin
RETVAL=0

prog="netmgr"
binpath="/usr/sbin/netmgr"
pidfile="/var/run/netmgr.pid"

write_hosts()
{
	hostname=`/usr/sbin/userconfig -read System ModelName`
	cnt=1
	mac=""
	while [ "$cnt" -lt 7 ]; do
		macaddress=`rtkmib mac|tr '[a-z]' '[A-Z]'`
		mac=$mac`echo $macaddress | cut -d: -f$cnt`
		cnt=$(($cnt+1))
	done
	echo "Set Hostname: ${hostname}-$mac"
	hostname "${hostname}-$mac"
	echo "127.0.0.1		localhost	localhost" > /etc/hosts
}

start()
{
	/etc/init.d/ipv4 init
	echo -n "Starting $prog: "
	$binpath
	write_hosts
	echo "."
}

stop()
{
	echo -n "Stopping $prog: "
	if [ -f $pidfile ]; then
		local line p
		read line < $pidfile
		kill $line
	fi
	echo "."
}

# See how we were called.
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0
