#!/bin/sh

# ddns: This starts and stops ddns.
#
# chkconfig: 2345 30 70
# description: ddns
#
# processname: /usr/sbin/ddns

# automatically export variables to the environment
set -a

PATH=/sbin:/bin:/usr/sbin:/usr/bin

prog="wanip_detect"
binpath="/usr/sbin/wanip_detect"
detect_interval=600
args="-i $detect_interval"

[ -f $binpath ] || exit

start(){
    echo -n "Starting $prog ... "
    $binpath $args >/dev/null 2>&1 &
    echo "."
}

#default --stop send signal 15 (SIGTERM)
stop(){
    echo -n "Stopping $prog ... "
    /usr/bin/killall $prog
    echo "."
}

# See how we are called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
