#!/bin/sh

# hnap_push_service: This starts and stops hnap_push_service.
#
# chkconfig: 2345 91 09
# description: hnap_push_service
#
# processname: /usr/sbin/hnap_push_service

# automatically export variables to the environment
set -a

PATH=/sbin:/bin:/usr/sbin:/usr/bin

prog="hnap_push_service"
binpath="/usr/sbin/hnap_push_service"

[ -f $binpath ] || exit

start(){
    echo -n "Starting $prog ... "
    $binpath &
    echo "."
}

#default --stop send signal 15 (SIGTERM)
stop(){
    echo -n "Stopping $prog ... "
    killall $prog
    echo "."
}

# See how we are called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
esac

exit 0
