#!/bin/sh /etc/rc.common
# Copyright (C) 2009-2012 OpenWrt.org

START=50

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

PROG=/usr/bin/mjpg_streamer

error() {
	echo "${initscript}:" "$@" 1>&2
}

section_enabled() {
	config_get_bool enabled "$1" 'enabled' 0
	[ $enabled -gt 0 ]
}

start_instance() {
	local s="$1"

	section_enabled "$s" || return 1

	config_get device "$s" 'device'
	config_get resolution "$s" 'resolution'
	config_get fps "$s" 'fps'
	config_get www "$s" 'www'
	config_get port "$s" 'port'

	[ -c "$device" ] || {
		error "device '$device' does not exist"
		return 1
	}

	service_start /usr/bin/mjpg_streamer --input "input_uvc.so \
		--device $device --fps $fps --resolution $resolution" \
		--output "output_http.so --www $www --port $port"
}

stop_instance() {
	local s="$1"

	section_enabled "$s" || return 1

	service_stop /usr/bin/mjpg_streamer
}

start() {
	#config_load 'mjpg-streamer'
	#config_foreach start_instance 'mjpg-streamer'
	service_start /usr/bin/mjpg_streamer -i "input_uvc.so -y -d /dev/video0 -r 320x240" -o "output_http.so -p 8801 -w /www/webcam"
	service_start /usr/sbin/crond
	crontab /etc/mjpg-streamer.conf
}

stop() {
	#config_load 'mjpg-streamer'
	#config_foreach stop_instance 'mjpg-streamer'
	service_stop /usr/sbin/crond
	for PID in `/bin/ps | grep mjpg_streamer | grep -v grep | awk  '{print $1}'`
	do
		/bin/kill -9 $PID
	done
	sleep 2
}

