#!/bin/sh
#
# Copyright (C) 2011 OpenWrt.org
#

pbx20_set_leds() {
	uci batch <<EOF
set system.sys_led=led
set system.sys_led.name='SYS'
set system.sys_led.sysfs='pbx20:green:sys'
set system.sys_led.trigger='heartbeat'


set system.usb_led=led
set system.usb_led.name='USB'
set system.usb_led.sysfs='pbx20:green:usb'
set system.usb_led.trigger='usbdev'
set system.usb_led.dev='1-1'
set system.usb_led.interval='50'

set system.wlan_led=led
set system.wlan_led.name='WLAN'
set system.wlan_led.sysfs='pbx20:green:wifi'
set system.wlan_led.trigger='netdev'
set system.wlan_led.dev='ra0'
set system.wlan_led.mode='link tx rx'

commit system
EOF
}

. /lib/ralink.sh

board=$(ralink_board_name)

if [ "${board}" == "pbx20" ]; then
	pbx20_set_leds
fi
