#!/bin/sh
#
# hwmon: This starts and stops hwmon.
#
# chkconfig: 2345 06 82
# description: hwmon
#
# processname: /usr/sbin/hwmon

# automatically export variables to the environment
set -a

PATH=/sbin:/bin:/usr/sbin:/usr/bin

prog="hwmon"
binpath="/usr/sbin/hwmon"

[ -f $binpath ] || exit

start(){
	echo -n "Starting $prog ... "
	$binpath &
	echo "."
}

#default --stop send signal 15 (SIGTERM)
stop(){
	echo -n "Stopping $prog ... "
	killall $prog
	echo "."
}

# See how we are called.
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0
