#!/bin/sh

# https: This starts and stops smtps.
#
# chkconfig: 2345 81 19
# description: smtps
#
# processname: /bin/stunnel

# automatically export variables to the environment
set -a

PATH=/sbin:/bin:/usr/sbin:/usr/bin

server_port=`/usr/sbin/userconfig -read EVENT_SERVER_SMTP ServerPort`
server_addr=`/usr/sbin/userconfig -read EVENT_SERVER_SMTP ServerAddr`
starttls_enable=`/usr/sbin/userconfig -read EVENT_SERVER_SMTP STARTTLS`

/usr/sbin/cfg -a w -p /var stunnel-smtps.conf smtps connect $server_addr:$server_port
if [ $starttls_enable = 0x01 ]; then
	/usr/sbin/cfg -a w -p /var stunnel-smtps.conf smtps protocol smtp
else	
	/usr/sbin/cfg -a d -p /var stunnel-smtps.conf smtps protocol
fi

start() {
	encrypt=`/usr/sbin/userconfig -read EVENT_SERVER_SMTP SSL`
	if [ $encrypt = 0x01 ]; then
		echo -n "Starting smtps stunnel:"
		export HOME=/; /bin/stunnel-smtps /var/stunnel-smtps.conf
	fi
}

stop() {
	/bin/kill `pidof stunnel-smtps`
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo $"Usage $0 {start|stop|restart}"
		exit 1
esac

exit $?
