#!/bin/sh

# camsvr: This starts and stops camsvr.
#
# chkconfig: 2345 80 10
# description: camsvr
#
# processname: /server/camsvr

# automatically export variables to the environment
set -a

PATH=/sbin:/bin:/usr/sbin:/usr/bin

start() {
	echo -n "Starting camsvr ... "
	cd /server; ./camsvr &
	echo "."
	/usr/sbin/swdog &
}

stop() {
	echo -n "Stopping camsvr ... "
	#kill `pidof camsvr`
	killall camsvr
	killall swdog
	echo "."
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo $"Usage $0 {start|stop|restart}"
		exit 1
esac

exit $?
