#!/bin/sh

# ddns: This starts and stops ddns.
#
# chkconfig: 2345 85 15
# description: ddns
#
# processname: /usr/sbin/ddns

# automatically export variables to the environment
set -a

PATH=/sbin:/bin:/usr/sbin:/usr/bin

prog="ddns"
binpath="/usr/sbin/ddns"
args="1>/dev/null 2>&1"
configpath="/usr/sbin/userconfig"

[ -f $binpath ] || exit

start(){

    enable=`$configpath -read DDNS Enable`
    if [ $enable == "0x01" ]; then
        echo -n "Starting $prog ... "
	/usr/bin/logger -t ipcam "Dynamic DNS register start"
        $binpath $args&
	echo "."
    fi
}

#default --stop send signal 15 (SIGTERM)
stop(){
    echo -n "Stopping $prog ... "
    /usr/bin/logger -t ipcam "Dynamic DNS register stop"
    /usr/bin/killall $prog
    echo "."
}

# See how we are called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
	sleep 1
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
esac

exit 0
