#!/bin/sh
# Program:
# 	Parse options of dhcp packet from dhcp6 server
# History:
# 2013/09/05	June.Chen for Linksys E1700
# 2011/11/02	Joan.Huang create
# 

RESOLV_V6_CONF="/tmp/resolv_v6.conf"

lan_if="br0"

add_ipv6_addr_with_DAD() {
	ip -6 addr add ${new_ip6_address}/${new_ip6_prefixlen} dev ${interface} scope global

	# repeatedly test whether newly added address passed
	# duplicate address detection (DAD)
	loop="1 2 3 4 5"
	for i in $loop; do
		sleep 1 # give the DAD some time

		# tentative flag == DAD is still not complete
		tentative=$(ip -6 addr show dev ${interface} tentative | grep ${new_ip6_address}/${new_ip6_prefixlen})
		# dadfailed flag == address is already in use somewhere else
		dadfailed=$(ip -6 addr show dev ${interface} dadfailed | grep ${new_ip6_address}/${new_ip6_prefixlen})

		if [ -n "${dadfailed}" ] ; then
			ip -6 addr del ${new_ip6_address}/${new_ip6_prefixlen} dev ${interface}
			return 3
		fi
		if [ -z "${tentative}" ] ; then
			# DAD is over
			return 1
		fi
	done

	return 1
}

set_ip6_na()
{	
	ip -6 addr del ${old_ip6_address}/${old_ip6_prefixlen} dev $lan_if scope global
	add_ipv6_addr_with_DAD
	result=$?
	return $result
}

set_ip6_dns()
{
	echo -n "" > $RESOLV_V6_CONF
	if [ -n "${new_dhcp6_name_servers}" ]; then
		for dns in ${new_dhcp6_name_servers} ; do
			echo "nameserver $dns" >> $RESOLV_V6_CONF
		done
	fi
}

#config dhcpv6 ip, prefix, etc.
# $1: 0: Stateful DHCPv6
#     1: Stateless DHCPv6
#     2: SLAAC
dhcp6_config()
{
	if [ -z "${new_ip6_prefix}" ] && [ -z "${new_ip6_address}" ]; then
		return 2
	fi

	case "${reason}" in
		BOUND6)
			if [ "$1" == "0" ]; then
				if [ -n "${new_ip6_address}" ] && [ -n "${new_ip6_prefixlen}" ]; then
					set_ip6_na
				fi
			fi
			set_ip6_dns
		;;
		RENEW6|REBIND6)
			if [ "$1" == "0" ]; then
				if [ -n "${new_ip6_address}" ] && [ -n "${new_ip6_prefixlen}" ]; then
					set_ip6_na
				fi
			fi
			set_ip6_dns
		;;
	esac

	return 0	
}

echo "" > /dev/console
echo "${reason}"  > /dev/console
echo "" > /dev/console

#mode=${ipv6_ra_conn_mode} 
mode=`cat /tmp/ipv6_ra_mode`

case "${reason}" in
	PREINIT6)
		ip link set $lan_if up

		#ip -6 addr flush dev $lan_if scope global permanent

		exit 0
	;;

	BOUND6|RENEW6|REBIND6)
		dhcp6_config $mode
		result=$?

		if [ "$result" != "0" ]; then
			exit $result
		fi
	;;

	DEPREF6)
		#if [ x${new_ip6_prefixlen} = x ] ; then
			exit 2
		#fi

		#ip -6 addr change ${new_ip6_address}/${new_ip6_prefixlen} dev $lan_if scope global preferred_lft 0
		#exit 0
	;;

	EXPIRE6|RELEASE6|STOP6)
		#if [ x${old_ip6_address} = x ] || [ x${old_ip6_prefixlen} = x ] ; then
		#	exit 2
		#fi

		#rm -f $RESOLV_V6_CONF
		#ip -6 addr del ${old_ip6_address}/${old_ip6_prefixlen} dev $lan_if
		#exit 0
	;;

esac

exit 0

