#!/bin/sh
#set -x

G_AppPath=""
G_Parameter_num=$#
G_Parameter_one=$1
G_InstallStausFile="/usr/local/app/installstatus/installstatus"  #用户存放app的安装状态
G_Parameter_all=$*

#判断参数是否合法
FunParamLegal()
{
	if [ ${G_Parameter_num} -ne 1 ];then
		xRouterLog 2 "CheckInstall" "FunParamLegal" "Parameter Err."
		exit 100
	fi
}

CheckInstallStatus()
{
	local TmpStaus=""
	
	TmpStaus=`cat ${G_InstallStausFile} | grep app_${G_Parameter_one} |awk -F ":" '{printf $2}' |awk -F " " '{printf $1}'`
	if [ "${TmpStaus}" == "" ];then
		xRouterLog 2 "CheckInstall" "CheckInstallStatus" "This app is not exist."
		exit 10
	else
#		echo "${TmpStaus},app_${G_Parameter_one}"
		xRouterLog 0 "CheckInstall" "CheckInstallStatus" "${TmpStaus},app_${G_Parameter_one}."
		exit ${TmpStaus}	
	fi	
}

xRouterLog 0 "CheckInstall" - "`basename $0` ${G_Parameter_all}"
#检查参数合法性
FunParamLegal
#检查安装状态
CheckInstallStatus