#!/bin/sh
#set -x

G_Parameter_num=$#
G_Parameter_one=$1
G_LastValue=""
G_AppPath=`dirname $0`
G_Url=""
G_TmpFile="/tmp/urlfile"
G_Parameter_all=$*

xRouterLog 0 "GetUrlByid" - "`basename $0` ${G_Parameter_all}"

#参数错误
if [ ${G_Parameter_num} -ne 1 ];then
	xRouterLog 2 "GetUrlByid" "-" "Parameter Err."
	exit 1
fi


wget -O ${G_TmpFile} "http://r.xcloud.cc/router/index.php?m=Index&a=getPluginsPath&id=${G_Parameter_one} " &>/dev/null
G_LastValue=$?
if [ ${G_ValueLast} -ne 0 ];then
	xRouterLog 2 "GetUrlByid" "-" "wget http://r.xcloud.cc/router/index.php?m=Index&a=getPluginsPath&id=${G_Parameter_one} Err."
fi


G_Url=`cat ${G_TmpFile}`

#得到的地址为空
if [ "${G_Url}" == "" ];then
	xRouterLog 2 "GetUrlByid" "-" "Url is Null."
	exit 2
else
	xRouterLog 0 "GetUrlByid" "-" "Url is ${G_Url}."
	echo "Success:Please check /tmp/urlfile"
	exit 0
fi



